kind: secret
name: token_docker
get:
  path: secrets
  name: token_docker_dronestock
---

kind: secret
name: password_ccr
get:
  path: secrets
  name: password_ccr
---


kind: pipeline
type: docker
name: 发布


clone:
  disable: true


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git:0.0.479
    pull: always

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/docker
    pull: always
    privileged: true
    volumes:
      - name: docker
        path: /var/lib/docker
    environment:
      PASSWORD_DOCKER:
        from_secret: token_docker
      PASSWORD_CCR:
        from_secret: password_ccr
    settings:
      repository: storezhang/onlyoffice
      tag: match(file('Dockerfile'), '.*(FROM onlyoffice/documentserver:(.*)\\\\s*).*')[2]
      registries:
        - username: storezhang
          password: $${PASSWORD_DOCKER}
        - hostname: ccr.ccs.tencentyun.com
          username: "160290688"
          password: $${PASSWORD_CCR}
          required: true


volumes:
  - name: docker
    host:
      path: /var/lib/cache/docker
